name: OIDC authentication test

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  verify-aws-authentication:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS authentication
        run: |
          aws sts get-caller-identity

          echo "Testing S3 access..."
          aws s3 ls
          
          echo "Testing IAM role permissions..."
          aws iam get-role --role-name github-actions-role