name: Create TF state storage with S3 and DynamoDB

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  TF_STATE_BUCKET: tf-state-bucket-01
  TF_LOCK_TABLE: tf-state-lock-01
  SSM_PARAM_NAME: /terraform/state-bucket-name

permissions:
  id-token: write
  contents: read

jobs:
  bootstrap:
    runs-on: ubuntu-22.04
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role
          aws-region: ${{ env.AWS_REGION }}

      - name: Create a New S3 Bucket
        id: create
        run: |
          BUCKET_PREFIX=$(openssl rand -hex 8)
          BUCKET_NAME="${BUCKET_PREFIX}-${TF_STATE_BUCKET}"
          echo "name=$BUCKET_NAME" >> $GITHUB_OUTPUT
          
          if [ "${AWS_REGION}" = "us-east-1" ]; then
            aws s3api create-bucket \
              --bucket ${BUCKET_NAME} || true
          else
            aws s3api create-bucket \
              --bucket ${BUCKET_NAME} \
              --region ${AWS_REGION} \
              --create-bucket-configuration LocationConstraint=${AWS_REGION} || true
          fi
          
          aws s3api put-bucket-versioning \
            --bucket ${BUCKET_NAME} \
            --versioning-configuration Status=Enabled || true
          
          aws s3api put-public-access-block \
            --bucket ${BUCKET_NAME} \
            --public-access-block-configuration \
              BlockPublicAcls=true,\
              IgnorePublicAcls=true,\
              BlockPublicPolicy=true,\
              RestrictPublicBuckets=true || true

      - name: Update SSM Parameter
        run: |
          aws ssm put-parameter \
            --name ${SSM_PARAM_NAME} \
            --value ${{ steps.create.outputs.name }} \
            --type String \
            --overwrite || true

      - name: Setup DynamoDB Table
        run: |
          aws dynamodb delete-table --table-name ${TF_LOCK_TABLE} || true
          aws dynamodb create-table \
            --table-name ${TF_LOCK_TABLE} \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST || true